# SPDX-License-Identifier: MIT-0
---
# tasks file for printing_3d

- name: Install 3D printing packages
  ansible.builtin.package:
    name: "{{ printing_3d_packages }}"
    state: present
  become: true
