# Copyright (c) 2026 T.R. Fullhart. All Rights Reserved.
---
# handlers file for syncthing

- name: Restart syncthing service
  ansible.builtin.systemd:
    name: "syncthing@{{ user_name }}.service"
    state: restarted
    scope: user
  become: true

- name: Restart syncthing service (Darwin)
  community.general.launchd:
    name: homebrew.mxcl.syncthing
    state: restarted
  become: true
