$ANSIBLE_VAULT;1.1;AES256
32663532653734643764666332666232313531626630316632613964356666633161333830313338
3839303332656236343161326134336265393730396636660a656534636662393261623835383333
36633434316361333935383765303134346266383364356462343839353831306133383830373032
6632353862646263350a376537313766366236366465383830656265323937666436306663623539
35333666393561346536393937333838336462353238666135613265383138613666646165323433
62633666656331386134663432313731343235623530303130653766393530343463383237626330
34663961663538653630396531393730653639616234326364346339633930333836613663373061
34653162343466616531633362363539386330636230393234346539303035383962393065386565
39316366663961363638396232316333353439666333633661623866396238346161393163653031
6661323962306666343764303865336334373366363964383636
