# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: "T.R. Fullhart <kayos@genetikayos.com>"
  description: SDR configuration role
  company: None
  license: MIT-0
  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
