# SPDX-License-Identifier: MIT-0
---
# defaults file for base

base_firewall_rules: []
base_package_names: []
base_sshd_package_names: []
base_zerotier_package_names: []
base_user_shell_package_names: []
base_user_groups: []
