# Copyright (c) 2026 T.R. Fullhart. All Rights Reserved.
galaxy_info:
  author: "T.R. Fullhart <kayos@genetikayos.com>"
  description: Syncthing file synchronization role
  company: None
  license: MIT-0
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: macOS
      versions:
        - all

  galaxy_tags: []

dependencies: []
