base_package_names:
  - curl
  - git
  - ansible-core
  - net-tools
  - vim
  - nano
  - omarchy-zsh
  - zsh

base_sshd_package_names:
  - openssh
base_sshd_unit_name: sshd
base_ufw_ssh_app_profile_name: SSH
