---
# Copyright (c) 2026 T.R. Fullhart. All Rights Reserved.

galaxy_info:
  author: T.R. Fullhart
  description: Configuration for ClockworkPi uConsole and similar small form factor devices
  company: Fleet
  license: All Rights Reserved
  min_ansible_version: "2.9"
  galaxy_tags:
    - hardware
    - uconsole
    - umpc

dependencies: []
