---
# Copyright (c) 2026 T.R. Fullhart. All Rights Reserved.

- name: "UConsole | Apply hardware-specific settings"
  ansible.builtin.include_tasks: "{{ ansible_facts.system | lower }}_configure.yml"
