# Copyright (c) 2026 T.R. Fullhart. All Rights Reserved.
---
- name: "Syncthing | Install Packages (Darwin)"
  community.general.homebrew:
    name: "{{ syncthing_package_names }}"
    state: present
