# Copyright (c) 2026 T.R. Fullhart. All Rights Reserved.
---
# Linux-specific tasks for enabling syncthing service

- name: "Syncthing | Enable and Start Service (Linux)"
  ansible.builtin.systemd:
    name: "syncthing@{{ user_name }}.service"
    state: started
    enabled: true
    scope: user
  become: true
  when: not ansible_check_mode
