# Copyright (c) 2026 T.R. Fullhart. All Rights Reserved.
galaxy_info:
  author: "T.R. Fullhart <kayos@genetikayos.com>"
  description: amateur_radio configuration
  company: None
  license: MIT-0
  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
